package dto

import "time"

// ============================================================================
// INVOICE REQUEST DTOs
// ============================================================================

// CreateInvoiceRequest represents invoice creation request
type CreateInvoiceRequest struct {
	InvoiceDate    string                     `json:"invoiceDate" binding:"required"`    // ISO date string
	DueDate        string                     `json:"dueDate" binding:"required"`        // ISO date string
	CustomerID     string                     `json:"customerId" binding:"required,uuid"`
	SalesOrderID   *string                    `json:"salesOrderId" binding:"omitempty,uuid"`
	DeliveryID     *string                    `json:"deliveryId" binding:"omitempty,uuid"`
	DiscountAmount string                     `json:"discountAmount" binding:"omitempty"` // decimal as string
	TaxAmount      string                     `json:"taxAmount" binding:"omitempty"`      // decimal as string
	Notes          *string                    `json:"notes" binding:"omitempty"`
	FakturPajakNo  *string                    `json:"fakturPajakNo" binding:"omitempty,max=100"`
	FakturPajakDate *string                   `json:"fakturPajakDate" binding:"omitempty"` // ISO date string
	Items          []CreateInvoiceItemRequest `json:"items" binding:"required,min=1,dive"`
}

// CreateInvoiceItemRequest represents invoice item creation request
type CreateInvoiceItemRequest struct {
	SalesOrderItemID *string `json:"salesOrderItemId" binding:"omitempty,uuid"`
	DeliveryItemID   *string `json:"deliveryItemId" binding:"omitempty,uuid"`
	ProductID        string  `json:"productId" binding:"required,uuid"`
	ProductUnitID    *string `json:"productUnitId" binding:"omitempty,uuid"`
	Quantity         string  `json:"quantity" binding:"required"`    // decimal as string, must be > 0
	UnitPrice        string  `json:"unitPrice" binding:"required"`   // decimal as string, must be >= 0
	DiscountPct      string  `json:"discountPct" binding:"omitempty"` // decimal as string
	DiscountAmt      string  `json:"discountAmt" binding:"omitempty"` // decimal as string
	Notes            *string `json:"notes" binding:"omitempty"`
}

// UpdateInvoiceRequest represents invoice update request
type UpdateInvoiceRequest struct {
	InvoiceDate     *string `json:"invoiceDate" binding:"omitempty"`
	DueDate         *string `json:"dueDate" binding:"omitempty"`
	CustomerID      *string `json:"customerId" binding:"omitempty,uuid"`
	DiscountAmount  *string `json:"discountAmount" binding:"omitempty"`
	TaxAmount       *string `json:"taxAmount" binding:"omitempty"`
	Notes           *string `json:"notes" binding:"omitempty"`
	FakturPajakNo   *string `json:"fakturPajakNo" binding:"omitempty,max=100"`
	FakturPajakDate *string `json:"fakturPajakDate" binding:"omitempty"`
}

// RecordInvoicePaymentRequest represents payment recording request for sales invoice
// Payment number is auto-generated by the system
type RecordInvoicePaymentRequest struct {
	PaymentDate   string  `json:"paymentDate" binding:"required"`   // ISO date string
	Amount        string  `json:"amount" binding:"required"`        // decimal as string, must be > 0
	PaymentMethod string  `json:"paymentMethod" binding:"required,oneof=CASH BANK_TRANSFER CHECK GIRO CREDIT_CARD DEBIT_CARD E_WALLET OTHER"`
	Reference     *string `json:"reference" binding:"omitempty,max=100"`
	BankAccountID *string `json:"bankAccountId" binding:"omitempty,uuid"`
	Notes         *string `json:"notes" binding:"omitempty"`
}

// InvoiceFilters represents invoice list filters
type InvoiceFilters struct {
	Search        string `form:"search"`         // Search in invoice number, customer name
	CustomerID    string `form:"customer_id"`    // Filter by customer
	PaymentStatus string `form:"payment_status"` // Filter by payment status
	DateFrom      string `form:"date_from"`      // ISO date string - invoice date range start
	DateTo        string `form:"date_to"`        // ISO date string - invoice date range end
	DueDateFrom   string `form:"due_date_from"`  // ISO date string - due date range start
	DueDateTo     string `form:"due_date_to"`    // ISO date string - due date range end
	Page          int    `form:"page" binding:"omitempty,min=1"`
	Limit         int    `form:"page_size" binding:"omitempty,min=1,max=100"`
	SortBy        string `form:"sort_by" binding:"omitempty,oneof=invoiceNumber invoiceDate dueDate totalAmount customerName createdAt"`
	SortOrder     string `form:"sort_order" binding:"omitempty,oneof=asc desc"`
}

// ============================================================================
// INVOICE RESPONSE DTOs
// ============================================================================

// InvoiceResponse represents invoice information response
type InvoiceResponse struct {
	ID              string                  `json:"id"`
	InvoiceNumber   string                  `json:"invoiceNumber"`
	InvoiceDate     string                  `json:"invoiceDate"` // ISO date string
	DueDate         string                  `json:"dueDate"`     // ISO date string
	CustomerID      string                  `json:"customerId"`
	CustomerName    string                  `json:"customerName"`
	CustomerCode    *string                 `json:"customerCode,omitempty"`
	SalesOrderID    *string                 `json:"salesOrderId,omitempty"`
	SONumber        *string                 `json:"soNumber,omitempty"`
	DeliveryID      *string                 `json:"deliveryId,omitempty"`
	DeliveryNumber  *string                 `json:"deliveryNumber,omitempty"`
	Subtotal        string                  `json:"subtotal"`        // decimal as string
	DiscountAmount  string                  `json:"discountAmount"`  // decimal as string
	TaxAmount       string                  `json:"taxAmount"`       // decimal as string
	TotalAmount     string                  `json:"totalAmount"`     // decimal as string
	PaidAmount      string                  `json:"paidAmount"`      // decimal as string
	RemainingAmount string                  `json:"remainingAmount"` // calculated: totalAmount - paidAmount
	PaymentStatus   string                  `json:"paymentStatus"`
	Notes           *string                 `json:"notes,omitempty"`
	FakturPajakNo   *string                 `json:"fakturPajakNo,omitempty"`
	FakturPajakDate *string                 `json:"fakturPajakDate,omitempty"` // ISO date string
	CreatedAt       time.Time               `json:"createdAt"`
	UpdatedAt       time.Time               `json:"updatedAt"`
	Items           []InvoiceItemResponse   `json:"items,omitempty"`
	Payments        []InvoicePaymentResponse `json:"payments,omitempty"`
}

// InvoiceItemResponse represents invoice item response
type InvoiceItemResponse struct {
	ID               string  `json:"id"`
	SalesOrderItemID *string `json:"salesOrderItemId,omitempty"`
	DeliveryItemID   *string `json:"deliveryItemId,omitempty"`
	ProductID        string  `json:"productId"`
	ProductCode      string  `json:"productCode"`
	ProductName      string  `json:"productName"`
	ProductUnitID    *string `json:"productUnitId,omitempty"`
	UnitName         string  `json:"unitName"`
	Quantity         string  `json:"quantity"`    // decimal as string
	UnitPrice        string  `json:"unitPrice"`   // decimal as string
	DiscountPct      string  `json:"discountPct"` // decimal as string
	DiscountAmt      string  `json:"discountAmt"` // decimal as string
	Subtotal         string  `json:"subtotal"`    // decimal as string
	Notes            *string `json:"notes,omitempty"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

// InvoicePaymentResponse represents payment transaction response
type InvoicePaymentResponse struct {
	ID            string    `json:"id"`
	PaymentNumber string    `json:"paymentNumber"`
	PaymentDate   string    `json:"paymentDate"` // ISO date string
	Amount        string    `json:"amount"`      // decimal as string
	PaymentMethod string    `json:"paymentMethod"`
	Reference     *string   `json:"reference,omitempty"`
	BankAccountID *string   `json:"bankAccountId,omitempty"`
	Notes         *string   `json:"notes,omitempty"`
	ReceivedBy    *string   `json:"receivedBy,omitempty"`
	ReceivedAt    *string   `json:"receivedAt,omitempty"` // ISO datetime string
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// InvoiceListResponse represents paginated list of invoices
type InvoiceListResponse struct {
	Data       []InvoiceResponse  `json:"data"`
	Pagination PaginationResponse `json:"pagination"`
}

// Payment constants are defined in payment_dto.go
