package dto

import "time"

// ============================================================================
// PURCHASE INVOICE REQUEST DTOs
// ============================================================================

// CreatePurchaseInvoiceRequest represents purchase invoice creation request
type CreatePurchaseInvoiceRequest struct {
	// InvoiceNumber is auto-generated by backend based on company format settings
	InvoiceDate     string                            `json:"invoiceDate" binding:"required"` // ISO date string
	DueDate         string                            `json:"dueDate" binding:"required"`     // ISO date string
	SupplierID      string                            `json:"supplierId" binding:"required,uuid"`
	PurchaseOrderID *string                           `json:"purchaseOrderId" binding:"omitempty,uuid"`
	GoodsReceiptID  *string                           `json:"goodsReceiptId" binding:"omitempty,uuid"`
	DiscountAmount  string                            `json:"discountAmount" binding:"omitempty"` // decimal as string
	TaxRate         string                            `json:"taxRate" binding:"omitempty"`        // decimal as string, default 11
	PaymentTermDays int                               `json:"paymentTermDays" binding:"omitempty,min=0,max=365"`
	Notes           *string                           `json:"notes" binding:"omitempty"`
	// Non-Goods Costs (Biaya Tambahan)
	ShippingCost         string  `json:"shippingCost" binding:"omitempty"`         // Biaya Pengiriman / Ongkir
	HandlingCost         string  `json:"handlingCost" binding:"omitempty"`         // Biaya Handling / Bongkar Muat
	OtherCost            string  `json:"otherCost" binding:"omitempty"`            // Biaya Lain-lain
	OtherCostDescription *string `json:"otherCostDescription" binding:"omitempty"` // Keterangan Biaya Lain-lain
	Items                []CreatePurchaseInvoiceItemRequest `json:"items" binding:"required,min=1,dive"`
}

// CreatePurchaseInvoiceItemRequest represents purchase invoice item creation request
type CreatePurchaseInvoiceItemRequest struct {
	PurchaseOrderItemID *string `json:"purchaseOrderItemId" binding:"omitempty,uuid"`
	GoodsReceiptItemID  *string `json:"goodsReceiptItemId" binding:"omitempty,uuid"`
	ProductID           string  `json:"productId" binding:"required,uuid"`
	UnitID              string  `json:"unitId" binding:"omitempty,uuid"` // Optional - defaults to product's base unit if not provided
	Quantity            string  `json:"quantity" binding:"required"`    // decimal as string, must be > 0
	UnitPrice           string  `json:"unitPrice" binding:"required"`   // decimal as string, must be >= 0
	DiscountAmount      string  `json:"discountAmount" binding:"omitempty"`  // decimal as string
	DiscountPct         string  `json:"discountPct" binding:"omitempty"`     // decimal as string
	TaxAmount           string  `json:"taxAmount" binding:"omitempty"`       // decimal as string
	Notes               *string `json:"notes" binding:"omitempty"`
}

// UpdatePurchaseInvoiceItemRequest represents purchase invoice item update request
type UpdatePurchaseInvoiceItemRequest struct {
	ID                  *string `json:"id" binding:"omitempty,uuid"`                  // Existing item ID (for reference), nil for new item
	PurchaseOrderItemID *string `json:"purchaseOrderItemId" binding:"omitempty,uuid"` // Reference to PO item (for tracking)
	GoodsReceiptItemID  *string `json:"goodsReceiptItemId" binding:"omitempty,uuid"`  // Reference to GRN item (for tracking invoiced qty)
	ProductID           string  `json:"productId" binding:"required,uuid"`
	UnitID              string  `json:"unitId" binding:"omitempty,uuid"`
	Quantity            string  `json:"quantity" binding:"required"`        // decimal as string, must be > 0
	UnitPrice           string  `json:"unitPrice" binding:"required"`       // decimal as string, must be >= 0
	DiscountAmount      string  `json:"discountAmount" binding:"omitempty"` // decimal as string
	DiscountPct         string  `json:"discountPct" binding:"omitempty"`    // decimal as string
	TaxAmount           string  `json:"taxAmount" binding:"omitempty"`      // decimal as string
	Notes               *string `json:"notes" binding:"omitempty"`
}

// UpdatePurchaseInvoiceRequest represents purchase invoice update request
type UpdatePurchaseInvoiceRequest struct {
	InvoiceDate     *string `json:"invoiceDate" binding:"omitempty"`
	DueDate         *string `json:"dueDate" binding:"omitempty"`
	SupplierID      *string `json:"supplierId" binding:"omitempty,uuid"`
	DiscountAmount  *string `json:"discountAmount" binding:"omitempty"`
	TaxRate         *string `json:"taxRate" binding:"omitempty"`
	PaymentTermDays *int    `json:"paymentTermDays" binding:"omitempty,min=0,max=365"`
	Notes           *string `json:"notes" binding:"omitempty"`
	Status          *string `json:"status" binding:"omitempty,oneof=DRAFT SUBMITTED APPROVED REJECTED PAID CANCELLED"`
	// Non-Goods Costs (Biaya Tambahan)
	ShippingCost         *string `json:"shippingCost" binding:"omitempty"`         // Biaya Pengiriman / Ongkir
	HandlingCost         *string `json:"handlingCost" binding:"omitempty"`         // Biaya Handling / Bongkar Muat
	OtherCost            *string `json:"otherCost" binding:"omitempty"`            // Biaya Lain-lain
	OtherCostDescription *string `json:"otherCostDescription" binding:"omitempty"` // Keterangan Biaya Lain-lain
	// Items - if provided, replaces all existing items
	Items []UpdatePurchaseInvoiceItemRequest `json:"items" binding:"omitempty,dive"`
}

// ApprovePurchaseInvoiceRequest represents approval request
type ApprovePurchaseInvoiceRequest struct {
	Notes *string `json:"notes" binding:"omitempty"`
}

// RejectPurchaseInvoiceRequest represents rejection request
type RejectPurchaseInvoiceRequest struct {
	Reason string `json:"reason" binding:"required,min=1,max=500"`
}

// CancelPurchaseInvoiceRequest represents cancellation request for approved invoices
type CancelPurchaseInvoiceRequest struct {
	Reason string `json:"reason" binding:"required,min=1,max=500"`
}

// RecordPaymentRequest represents payment recording request
type RecordPaymentRequest struct {
	PaymentNumber string  `json:"paymentNumber" binding:"required,min=1,max=100"`
	PaymentDate   string  `json:"paymentDate" binding:"required"` // ISO date string
	Amount        string  `json:"amount" binding:"required"`      // decimal as string, must be > 0
	PaymentMethod string  `json:"paymentMethod" binding:"required,oneof=CASH BANK_TRANSFER CHECK GIRO CREDIT_CARD OTHER"`
	Reference     *string `json:"reference" binding:"omitempty,max=255"`
	BankAccountID *string `json:"bankAccountId" binding:"omitempty,uuid"`
	Notes         *string `json:"notes" binding:"omitempty"`
}

// PurchaseInvoiceFilters represents purchase invoice list filters
type PurchaseInvoiceFilters struct {
	Search         string  `form:"search"`          // Search in invoice number, supplier name
	SupplierID     string  `form:"supplier_id"`     // Filter by supplier
	Status         string  `form:"status"`          // Filter by status
	PaymentStatus  string  `form:"payment_status"`  // Filter by payment status
	DateFrom       string  `form:"date_from"`       // ISO date string - invoice date range start
	DateTo         string  `form:"date_to"`         // ISO date string - invoice date range end
	DueDateFrom    string  `form:"due_date_from"`   // ISO date string - due date range start
	DueDateTo      string  `form:"due_date_to"`     // ISO date string - due date range end
	Page           int     `form:"page" binding:"omitempty,min=1"`
	Limit          int     `form:"page_size" binding:"omitempty,min=1,max=100"`
	SortBy         string  `form:"sort_by" binding:"omitempty,oneof=invoiceNumber invoiceDate dueDate totalAmount createdAt"`
	SortOrder      string  `form:"sort_order" binding:"omitempty,oneof=asc desc"`
}

// ============================================================================
// PURCHASE INVOICE RESPONSE DTOs
// ============================================================================

// PurchaseInvoiceResponse represents purchase invoice information response
type PurchaseInvoiceResponse struct {
	ID              string                            `json:"id"`
	InvoiceNumber   string                            `json:"invoiceNumber"`
	InvoiceDate     string                            `json:"invoiceDate"` // ISO date string
	DueDate         string                            `json:"dueDate"`     // ISO date string
	SupplierID      string                            `json:"supplierId"`
	SupplierName    string                            `json:"supplierName"`
	SupplierCode    *string                           `json:"supplierCode,omitempty"`
	PurchaseOrderID *string                           `json:"purchaseOrderId,omitempty"`
	PONumber        *string                           `json:"poNumber,omitempty"`
	GoodsReceiptID  *string                           `json:"goodsReceiptId,omitempty"`
	GRNumber        *string                           `json:"grNumber,omitempty"`
	SubtotalAmount  string                            `json:"subtotalAmount"`  // decimal as string
	DiscountAmount  string                            `json:"discountAmount"`  // decimal as string
	TaxAmount       string                            `json:"taxAmount"`       // decimal as string
	TaxRate         string                            `json:"taxRate"`         // decimal as string
	TotalAmount     string                            `json:"totalAmount"`     // decimal as string
	PaidAmount      string                            `json:"paidAmount"`      // decimal as string
	RemainingAmount string                            `json:"remainingAmount"` // decimal as string
	// Non-Goods Costs (Biaya Tambahan)
	ShippingCost         string  `json:"shippingCost"`                       // Biaya Pengiriman / Ongkir
	HandlingCost         string  `json:"handlingCost"`                       // Biaya Handling / Bongkar Muat
	OtherCost            string  `json:"otherCost"`                          // Biaya Lain-lain
	OtherCostDescription *string `json:"otherCostDescription,omitempty"`     // Keterangan Biaya Lain-lain
	TotalNonGoodsCost    string  `json:"totalNonGoodsCost"`                  // Total Biaya Tambahan (computed)
	PaymentTermDays int                               `json:"paymentTermDays"`
	Status          string                            `json:"status"`
	PaymentStatus   string                            `json:"paymentStatus"`
	Notes           *string                           `json:"notes,omitempty"`
	ApprovedBy      *string                           `json:"approvedBy,omitempty"`
	ApprovedAt      *string                           `json:"approvedAt,omitempty"` // ISO datetime string
	RejectedBy      *string                           `json:"rejectedBy,omitempty"`
	RejectedAt      *string                           `json:"rejectedAt,omitempty"` // ISO datetime string
	RejectedReason  *string                           `json:"rejectedReason,omitempty"`
	TaxInvoiceNumber *string                          `json:"taxInvoiceNumber,omitempty"`
	TaxInvoiceDate   *string                          `json:"taxInvoiceDate,omitempty"` // ISO date string
	CreatedBy       string                            `json:"createdBy"`
	UpdatedBy       *string                           `json:"updatedBy,omitempty"`
	CreatedAt       time.Time                         `json:"createdAt"`
	UpdatedAt       time.Time                         `json:"updatedAt"`
	Items           []PurchaseInvoiceItemResponse     `json:"items,omitempty"`
	Payments        []PurchaseInvoicePaymentResponse  `json:"payments,omitempty"`
}

// PurchaseInvoiceItemResponse represents purchase invoice item response
type PurchaseInvoiceItemResponse struct {
	ID                  string  `json:"id"`
	PurchaseOrderItemID *string `json:"purchaseOrderItemId,omitempty"`
	GoodsReceiptItemID  *string `json:"goodsReceiptItemId,omitempty"`
	ProductID           string  `json:"productId"`
	ProductCode         string  `json:"productCode"`
	ProductName         string  `json:"productName"`
	UnitID              string  `json:"unitId"`
	UnitName            string  `json:"unitName"`
	Quantity            string  `json:"quantity"`       // decimal as string
	UnitPrice           string  `json:"unitPrice"`      // decimal as string
	DiscountAmount      string  `json:"discountAmount"` // decimal as string
	DiscountPct         string  `json:"discountPct"`    // decimal as string
	TaxAmount           string  `json:"taxAmount"`      // decimal as string
	LineTotal           string  `json:"lineTotal"`      // decimal as string
	Notes               *string `json:"notes,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}

// PurchaseInvoicePaymentResponse represents payment transaction response
type PurchaseInvoicePaymentResponse struct {
	ID            string    `json:"id"`
	PaymentNumber string    `json:"paymentNumber"`
	PaymentDate   string    `json:"paymentDate"` // ISO date string
	Amount        string    `json:"amount"`      // decimal as string
	PaymentMethod string    `json:"paymentMethod"`
	Reference     *string   `json:"reference,omitempty"`
	BankAccountID *string   `json:"bankAccountId,omitempty"`
	Notes         *string   `json:"notes,omitempty"`
	CreatedBy     string    `json:"createdBy"`
	UpdatedBy     *string   `json:"updatedBy,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// PurchaseInvoiceListResponse represents paginated list of purchase invoices
type PurchaseInvoiceListResponse struct {
	Data       []PurchaseInvoiceResponse `json:"data"`
	Pagination PaginationResponse        `json:"pagination"`
}

// PaginationResponse represents pagination metadata
type PaginationResponse struct {
	Page       int  `json:"page"`
	Limit      int  `json:"limit"`
	Total      int64 `json:"total"`
	TotalPages int  `json:"totalPages"`
}

// ============================================================================
// HELPER CONSTANTS
// ============================================================================

// Purchase Invoice Status Constants
const (
	PurchaseInvoiceStatusDraft     = "DRAFT"
	PurchaseInvoiceStatusSubmitted = "SUBMITTED"
	PurchaseInvoiceStatusApproved  = "APPROVED"
	PurchaseInvoiceStatusRejected  = "REJECTED"
	PurchaseInvoiceStatusPaid      = "PAID"
	PurchaseInvoiceStatusCancelled = "CANCELLED"
)

// Payment Status and Payment Method constants are defined in payment_dto.go
