package dto

// ============================================================================
// SUPPLIER PAYMENT REQUEST DTOs
// ============================================================================

// CreateSupplierPaymentRequest represents supplier payment creation request
type CreateSupplierPaymentRequest struct {
	// PaymentNumber is auto-generated by backend based on company format settings
	PaymentDate     string  `json:"paymentDate" binding:"required"`     // ISO date string
	SupplierID      string  `json:"supplierId" binding:"required,uuid"`
	PurchaseOrderID *string `json:"purchaseOrderId" binding:"omitempty,uuid"`
	Amount          string  `json:"amount" binding:"required"`      // decimal as string, must be > 0
	PaymentMethod   string  `json:"paymentMethod" binding:"required,oneof=CASH BANK_TRANSFER CHECK GIRO CREDIT_CARD OTHER"`
	Reference       *string `json:"reference" binding:"omitempty,max=100"`
	BankAccountID   *string `json:"bankAccountId" binding:"omitempty,uuid"`
	Notes           *string `json:"notes" binding:"omitempty"`
}

// UpdateSupplierPaymentRequest represents supplier payment update request
type UpdateSupplierPaymentRequest struct {
	PaymentDate     *string `json:"paymentDate" binding:"omitempty"`
	SupplierID      *string `json:"supplierId" binding:"omitempty,uuid"`
	PurchaseOrderID *string `json:"purchaseOrderId" binding:"omitempty,uuid"`
	Amount          *string `json:"amount" binding:"omitempty"`
	PaymentMethod   *string `json:"paymentMethod" binding:"omitempty,oneof=CASH BANK_TRANSFER CHECK GIRO CREDIT_CARD OTHER"`
	Reference       *string `json:"reference" binding:"omitempty,max=100"`
	BankAccountID   *string `json:"bankAccountId" binding:"omitempty,uuid"`
	Notes           *string `json:"notes" binding:"omitempty"`
}

// ApproveSupplierPaymentRequest represents payment approval request
type ApproveSupplierPaymentRequest struct {
	Notes *string `json:"notes" binding:"omitempty"`
}

// SupplierPaymentFilters represents supplier payment list filters
type SupplierPaymentFilters struct {
	Search        string `form:"search"`         // Search in payment number, supplier name, reference
	SupplierID    string `form:"supplier_id"`    // Filter by supplier
	PaymentMethod string `form:"payment_method"` // Filter by payment method
	Status        string `form:"status"`         // Filter by status (PENDING, APPROVED, etc.)
	DateFrom      string `form:"date_from"`      // ISO date string - payment date range start
	DateTo        string `form:"date_to"`        // ISO date string - payment date range end
	AmountMin     string `form:"amount_min"`     // Minimum amount filter
	AmountMax     string `form:"amount_max"`     // Maximum amount filter
	Page          int    `form:"page" binding:"omitempty,min=1"`
	Limit         int    `form:"page_size" binding:"omitempty,min=1,max=100"`
	SortBy        string `form:"sort_by" binding:"omitempty,oneof=paymentNumber paymentDate supplierName amount createdAt"`
	SortOrder     string `form:"sort_order" binding:"omitempty,oneof=asc desc"`
}

// ============================================================================
// SUPPLIER PAYMENT RESPONSE DTOs
// ============================================================================

// SupplierPaymentResponse represents supplier payment information response
type SupplierPaymentResponse struct {
	ID              string  `json:"id"`
	PaymentNumber   string  `json:"paymentNumber"`
	PaymentDate     string  `json:"paymentDate"` // ISO date string
	SupplierID      string  `json:"supplierId"`
	SupplierName    string  `json:"supplierName"`
	SupplierCode    *string `json:"supplierCode,omitempty"`
	PurchaseOrderID *string `json:"purchaseOrderId,omitempty"`
	PONumber        *string `json:"poNumber,omitempty"`
	Amount          string  `json:"amount"`
	PaymentMethod   string  `json:"paymentMethod"`
	Reference       *string `json:"reference,omitempty"`
	BankAccountID   *string `json:"bankAccountId,omitempty"`
	BankAccountName *string `json:"bankAccountName,omitempty"`
	Notes           *string `json:"notes,omitempty"`
	Status          *string `json:"status,omitempty"`
	ApprovedBy      *string `json:"approvedBy,omitempty"`
	ApprovedAt      *string `json:"approvedAt,omitempty"` // ISO datetime string
	CreatedBy       string  `json:"createdBy"`
	UpdatedBy       *string `json:"updatedBy,omitempty"`
	CreatedAt       string  `json:"createdAt"` // ISO datetime string
	UpdatedAt       string  `json:"updatedAt"` // ISO datetime string
}

// SupplierPaymentListResponse represents paginated supplier payment list response
type SupplierPaymentListResponse struct {
	Data       []SupplierPaymentResponse `json:"data"`
	Pagination PaginationResponse        `json:"pagination"`
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

// SetDefaultPagination sets default values for pagination
func (f *SupplierPaymentFilters) SetDefaultPagination() {
	if f.Page < 1 {
		f.Page = 1
	}
	if f.Limit < 1 {
		f.Limit = 20 // Default page size
	}
	if f.SortBy == "" {
		f.SortBy = "payment_date" // Use snake_case for database column
	} else {
		// Map camelCase to snake_case for database columns
		f.SortBy = f.MapSortByToColumn()
	}
	if f.SortOrder == "" {
		f.SortOrder = "desc"
	}
}

// MapSortByToColumn converts camelCase sort fields to snake_case database columns
func (f *SupplierPaymentFilters) MapSortByToColumn() string {
	sortByMap := map[string]string{
		"paymentNumber": "payment_number",
		"paymentDate":   "payment_date",
		"supplierName":  "supplier_name",
		"amount":        "amount",
		"createdAt":     "created_at",
	}

	if mapped, ok := sortByMap[f.SortBy]; ok {
		return mapped
	}
	return f.SortBy // Return as-is if no mapping found
}
