/**
 * Create Invoice Form Component
 *
 * Professional form for creating new purchase invoices with:
 * - Supplier selection
 * - Invoice header (dates, numbers, references)
 * - Line items management
 * - Financial calculations (subtotal, tax, discount, total)
 * - Real-time validation
 */

"use client";

import { useState, useEffect } from "react";
import { useSelector } from "react-redux";
import {
  FileText,
  Building2,
  Calendar,
  Package,
  Save,
  AlertCircle,
  Trash2,
  DollarSign,
  Truck,
  HandCoins,
  ReceiptText,
  AlertTriangle,
  ShieldCheck,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useCreatePurchaseInvoiceMutation } from "@/store/services/purchaseInvoiceApi";
import { useListSuppliersQuery } from "@/store/services/supplierApi";
import { useListPurchaseOrdersQuery, useGetPurchaseOrderQuery } from "@/store/services/purchaseOrderApi";
import { useListGoodsReceiptsQuery, useGetGoodsReceiptQuery } from "@/store/services/goodsReceiptApi";
import { useGetCompanyQuery } from "@/store/services/companyApi";
import {
  INVOICE_CONTROL_POLICY_LABELS,
  type InvoiceControlPolicy,
} from "@/types/company.types";
import { Badge } from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { toast } from "sonner";
import type { CreatePurchaseInvoiceRequest } from "@/types/purchase-invoice.types";
import {
  PURCHASE_ORDER_STATUS_LABELS,
  PURCHASE_ORDER_STATUS_COLORS,
  type PurchaseOrderStatus,
} from "@/types/purchase-order.types";
import type { GoodsReceiptResponse } from "@/types/goods-receipt.types";
import { selectActiveCompany } from "@/store/slices/companySlice";
import { CheckCircle2, AlertCircle as AlertCircleIcon, Clock } from "lucide-react";

interface CreateInvoiceFormProps {
  onSuccess?: (invoiceId: string) => void;
  onCancel?: () => void;
}

interface InvoiceItem {
  id: string;
  productId: string;
  productCode: string;
  productName: string;
  quantity: string;
  unitId: string; // UUID of the product unit
  unitName: string;
  unitPrice: string;
  discountPercent: string;
  discountAmount: string;
  taxPercent: string;
  taxAmount: string;
  totalAmount: string;
  // PO/GRN reference fields for backend validation
  purchaseOrderItemId?: string; // Reference to PO item for qty validation
  goodsReceiptItemId?: string; // Reference to GRN item
  // Invoice control fields
  maxInvoiceableQty: number; // Max qty that can be invoiced based on policy
  orderedQty: number; // Qty ordered in PO
  receivedQty: number; // Qty received in GRN
  invoicedQty: number; // Qty already invoiced
}

export function CreateInvoiceForm({
  onSuccess,
  onCancel,
}: CreateInvoiceFormProps) {
  const [createInvoice, { isLoading }] = useCreatePurchaseInvoiceMutation();

  // Form state
  const [formData, setFormData] = useState({
    supplierId: "",
    // invoiceNumber is auto-generated by backend
    invoiceDate: new Date().toISOString().split("T")[0],
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0], // 30 days from now
    purchaseOrderId: "",
    purchaseOrderNumber: "",
    goodsReceiptId: "",
    goodsReceiptNumber: "",
    notes: "",
    taxPercentage: "11", // Default PPN 11%
    // Header-level discount (diskon faktur)
    headerDiscountAmount: "0",
    // Biaya non-barang (header level)
    shippingCost: "0", // Biaya Pengiriman/Ongkir
    handlingCost: "0", // Biaya Handling
    otherCost: "0", // Biaya Lain-lain
    otherCostDescription: "", // Deskripsi Biaya Lain-lain
  });

  // Fetch active suppliers for dropdown
  const { data: suppliersData, isLoading: isLoadingSuppliers } = useListSuppliersQuery({
    isActive: true,
    pageSize: 100
  });
  const suppliers = suppliersData?.data || [];

  // Invoiceable PO statuses - POs that can have invoices created
  const INVOICEABLE_STATUSES: PurchaseOrderStatus[] = ["CONFIRMED", "COMPLETED", "SHORT_CLOSED"];

  // Fetch POs filtered by selected supplier (fetch all, filter on frontend)
  const { data: purchaseOrdersData, isFetching: isLoadingPOs } = useListPurchaseOrdersQuery(
    {
      supplierId: formData.supplierId,
      pageSize: 100
    },
    {
      skip: !formData.supplierId // Only fetch when supplier is selected
    }
  );
  // Filter to only show invoiceable POs (CONFIRMED, COMPLETED, SHORT_CLOSED)
  const purchaseOrders = (purchaseOrdersData?.data || []).filter(po =>
    INVOICEABLE_STATUSES.includes(po.status as PurchaseOrderStatus)
  );

  // Fetch Goods Receipts for the selected PO (fetch all, filter on frontend)
  const { data: goodsReceiptsData, isFetching: isLoadingGRs } = useListGoodsReceiptsQuery(
    {
      purchaseOrderId: formData.purchaseOrderId,
      pageSize: 100
    },
    {
      skip: !formData.purchaseOrderId // Only fetch when PO is selected
    }
  );
  // Filter to only show GRNs that have accepted items (ACCEPTED or PARTIAL status)
  const goodsReceipts = (goodsReceiptsData?.data || []).filter(gr =>
    gr.status === "ACCEPTED" || gr.status === "PARTIAL"
  );

  // Fetch selected PO details for auto-populate
  const { data: selectedPOData } = useGetPurchaseOrderQuery(
    formData.purchaseOrderId,
    { skip: !formData.purchaseOrderId }
  );

  // Fetch selected GRN details (with items) for auto-populate
  const { data: selectedGRData } = useGetGoodsReceiptQuery(
    formData.goodsReceiptId,
    { skip: !formData.goodsReceiptId }
  );

  // Fetch company settings for invoice control policy and tolerance
  const { data: companyData } = useGetCompanyQuery();
  const invoiceControlPolicy = (companyData?.invoiceControlPolicy || "ORDERED") as InvoiceControlPolicy;
  const invoiceTolerancePct = companyData?.invoiceTolerancePct || 0;

  // Get active company from Redux for PKP status
  const activeCompany = useSelector(selectActiveCompany);

  const [items, setItems] = useState<InvoiceItem[]>([]);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [touched, setTouched] = useState<Record<string, boolean>>({});

  // Get badge info for a specific GRN from the list (used in dropdown options)
  const getGRNBadgeFromList = (gr: GoodsReceiptResponse) => {
    switch (gr.invoiceStatus) {
      case 'FULL':
        return {
          label: 'Invoice Penuh',
          color: 'bg-red-100 text-red-800',
          icon: CheckCircle2,
          disabled: true,
          tooltip: 'Semua item dari GRN ini sudah sepenuhnya di-invoice',
        };
      case 'PARTIAL':
        return {
          label: 'Invoice Sebagian',
          color: 'bg-orange-100 text-orange-800',
          icon: AlertCircleIcon,
          disabled: false,
          tooltip: 'Beberapa item sudah di-invoice. Hanya item dengan sisa qty yang akan ditambahkan.',
        };
      case 'NONE':
      default:
        return {
          label: 'Belum Invoice',
          color: 'bg-green-100 text-green-800',
          icon: Clock,
          disabled: false,
          tooltip: 'Semua item masih tersedia untuk di-invoice',
        };
    }
  };

  // Check if the selected GRN is fully invoiced
  const selectedGRN = goodsReceipts.find(gr => gr.id === formData.goodsReceiptId);
  const isSelectedGRNFullyInvoiced = selectedGRN?.invoiceStatus === 'FULL';

  // Initialize tax percentage based on PKP status
  useEffect(() => {
    if (activeCompany) {
      const taxRate = activeCompany.isPKP ? (activeCompany.ppnRate ?? 11).toString() : "0";
      setFormData(prev => ({ ...prev, taxPercentage: taxRate }));
    }
  }, [activeCompany]);

  // Auto-populate items from GRN when GRN data is loaded
  // Option 4: Smart population - only add items with remaining invoiceable qty > 0
  useEffect(() => {
    if (selectedGRData && selectedGRData.items && selectedGRData.items.length > 0 && items.length === 0) {
      let skippedItems = 0;
      const skippedProductNames: string[] = [];

      const newItems = selectedGRData.items
        .filter(item => parseFloat(item.acceptedQty) > 0)
        .map((item, index) => {
          // Get unit price from PO if available
          const poItem = selectedPOData?.items?.find(
            poi => poi.productId === item.productId
          );
          const unitPrice = poItem?.unitPrice || "0";
          const price = parseFloat(unitPrice);
          const discPct = parseFloat(poItem?.discountPct || "0");
          const taxPct = parseFloat(formData.taxPercentage);

          // Get unitId with fallbacks: GRN item > GRN productUnit > PO item > PO productUnit
          // Note: unitId can be empty if product uses base unit (no conversion unit) - this is valid
          const unitId = item.productUnitId ||
                        item.productUnit?.id ||
                        poItem?.productUnitId ||
                        poItem?.productUnit?.id ||
                        "";

          // Calculate invoice control fields
          // Use GRN-item-level invoicedQty (not PO-level) for accurate remaining calculation
          const orderedQty = parseFloat(poItem?.quantity || "0");
          const acceptedQty = parseFloat(item.acceptedQty || "0");
          const grnItemInvoicedQty = parseFloat(item.invoicedQty || "0");

          // Calculate remaining invoiceable qty = acceptedQty - already invoiced for this GRN item
          const remainingQty = Math.max(0, acceptedQty - grnItemInvoicedQty);

          // Apply tolerance percentage for max limit
          const toleranceMultiplier = 1 + (invoiceTolerancePct / 100);
          const maxInvoiceableQty = remainingQty * toleranceMultiplier;

          // Skip items with no remaining invoiceable qty
          if (remainingQty <= 0) {
            skippedItems++;
            skippedProductNames.push(item.product?.name || item.productId);
            return null; // Will be filtered out
          }

          // Calculate totals based on REMAINING qty (not full accepted qty)
          const subtotal = remainingQty * price;
          const discount = (subtotal * discPct) / 100;
          const taxableAmount = subtotal - discount;
          const tax = (taxableAmount * taxPct) / 100;
          const total = taxableAmount + tax;

          return {
            id: `item-${Date.now()}-${index}`,
            productId: item.productId,
            productCode: item.product?.code || "",
            productName: item.product?.name || "",
            quantity: remainingQty.toString(),
            unitId: unitId,
            unitName: item.productUnit?.unitName || item.product?.baseUnit || "PCS",
            unitPrice: unitPrice,
            discountPercent: poItem?.discountPct || "0",
            discountAmount: discount.toFixed(2),
            taxPercent: formData.taxPercentage,
            taxAmount: tax.toFixed(2),
            totalAmount: total.toFixed(2),
            // PO/GRN reference fields for backend validation
            purchaseOrderItemId: item.purchaseOrderItemId || poItem?.id,
            goodsReceiptItemId: item.id,
            // Invoice control fields
            maxInvoiceableQty,
            orderedQty,
            receivedQty: acceptedQty, // Use GRN accepted qty as "received" for display
            invoicedQty: grnItemInvoicedQty, // GRN-item level invoiced qty
          };
        })
        .filter((item) => item !== null) as InvoiceItem[]; // Filter out null items and cast to proper type

      if (newItems.length > 0) {
        setItems(newItems);

        if (skippedItems > 0) {
          // Some items were added, but some were skipped
          toast.info("Items Ditambahkan (Sebagian)", {
            description: `${newItems.length} item ditambahkan. ${skippedItems} item dilewati karena sudah sepenuhnya di-invoice: ${skippedProductNames.slice(0, 3).join(", ")}${skippedProductNames.length > 3 ? ` dan ${skippedProductNames.length - 3} lainnya` : ""}`,
            duration: 6000,
          });
        } else {
          toast.success("Items Ditambahkan", {
            description: `${newItems.length} item dari GRN telah ditambahkan ke faktur`,
          });
        }
      } else if (skippedItems > 0) {
        // All items were skipped - GRN is fully invoiced
        toast.warning("Tidak Ada Item yang Dapat Di-invoice", {
          description: `Semua ${skippedItems} item dari GRN ini sudah sepenuhnya di-invoice. Silakan pilih GRN lain.`,
          duration: 8000,
        });
      }
    }
  }, [selectedGRData, selectedPOData, formData.taxPercentage, invoiceControlPolicy, invoiceTolerancePct]);

  const handleChange = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: "" }));
    }
  };

  const handleBlur = (field: string) => {
    setTouched((prev) => ({ ...prev, [field]: true }));
  };

  const formatCurrency = (value: string | number): string => {
    const num = typeof value === "string" ? parseFloat(value || "0") : value;
    if (isNaN(num)) return "Rp 0";
    // Check if number has decimal part
    const hasDecimal = num % 1 !== 0;
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      minimumFractionDigits: 0,
      maximumFractionDigits: hasDecimal ? 2 : 0,
    }).format(num);
  };

  // Note: Items are auto-populated from GRN only (GRN Wajib mode)
  // No manual item addition allowed

  // Remove item row (still allowed for adjustments)
  const handleRemoveItem = (itemId: string) => {
    setItems(items.filter((item) => item.id !== itemId));
  };

  // Update item field
  const handleItemChange = (itemId: string, field: keyof InvoiceItem, value: string) => {
    setItems((prevItems) =>
      prevItems.map((item) => {
        if (item.id !== itemId) return item;

        const updated = { ...item, [field]: value };

        // Recalculate if numeric fields changed
        if (["quantity", "unitPrice", "discountPercent", "taxPercent"].includes(field)) {
          const qty = parseFloat(updated.quantity || "0");
          const price = parseFloat(updated.unitPrice || "0");
          const discPct = parseFloat(updated.discountPercent || "0");
          const taxPct = parseFloat(updated.taxPercent || "0");

          const subtotal = qty * price;
          const discount = (subtotal * discPct) / 100;
          const taxableAmount = subtotal - discount;
          const tax = (taxableAmount * taxPct) / 100;
          const total = taxableAmount + tax;

          updated.discountAmount = discount.toFixed(2);
          updated.taxAmount = tax.toFixed(2);
          updated.totalAmount = total.toFixed(2);
        }

        return updated;
      })
    );
  };

  // Calculate totals including non-goods costs
  const calculateTotals = () => {
    // Items subtotal (before discount)
    const subtotal = items.reduce((sum, item) => {
      const qty = parseFloat(item.quantity || "0");
      const price = parseFloat(item.unitPrice || "0");
      return sum + qty * price;
    }, 0);

    // Line-level discount total
    const lineDiscount = items.reduce((sum, item) => {
      return sum + parseFloat(item.discountAmount || "0");
    }, 0);

    // Header-level discount (diskon faktur)
    const headerDiscount = parseFloat(formData.headerDiscountAmount || "0");

    // Total discount = line discount + header discount
    const totalDiscount = lineDiscount + headerDiscount;

    // Total tax from items
    const totalTax = items.reduce((sum, item) => {
      return sum + parseFloat(item.taxAmount || "0");
    }, 0);

    // Non-goods costs (header level)
    const shippingCost = parseFloat(formData.shippingCost || "0");
    const handlingCost = parseFloat(formData.handlingCost || "0");
    const otherCost = parseFloat(formData.otherCost || "0");
    const totalNonGoodsCost = shippingCost + handlingCost + otherCost;

    // Grand total = subtotal - discount + tax + non-goods costs
    const total = subtotal - totalDiscount + totalTax + totalNonGoodsCost;

    return {
      subtotal,
      lineDiscount,
      headerDiscount,
      totalDiscount,
      totalTax,
      shippingCost,
      handlingCost,
      otherCost,
      totalNonGoodsCost,
      total,
    };
  };

  const totals = calculateTotals();

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};

    // Required fields
    if (!formData.supplierId.trim()) {
      newErrors.supplierId = "Supplier wajib dipilih";
    }
    // GRN is required (GRN Wajib mode)
    if (!formData.goodsReceiptId) {
      newErrors.goodsReceiptId = "Penerimaan Barang (GRN) wajib dipilih";
    } else {
      // Check if selected GRN is fully invoiced
      const selectedGR = goodsReceipts.find(gr => gr.id === formData.goodsReceiptId);
      if (selectedGR?.invoiceStatus === 'FULL') {
        newErrors.goodsReceiptId = "GRN ini sudah sepenuhnya di-invoice. Pilih GRN lain.";
      }
    }
    // invoiceNumber is auto-generated by backend, no validation needed
    if (!formData.invoiceDate) {
      newErrors.invoiceDate = "Tanggal faktur wajib diisi";
    }
    if (!formData.dueDate) {
      newErrors.dueDate = "Jatuh tempo wajib diisi";
    }

    // Date validation
    if (formData.invoiceDate && formData.dueDate) {
      const invoiceDate = new Date(formData.invoiceDate);
      const dueDate = new Date(formData.dueDate);
      if (dueDate < invoiceDate) {
        newErrors.dueDate = "Jatuh tempo tidak boleh lebih awal dari tanggal faktur";
      }
    }

    // Items validation
    if (items.length === 0) {
      newErrors.items = "Minimal harus ada 1 item";
    } else {
      items.forEach((item, index) => {
        if (!item.productName.trim()) {
          newErrors[`item-${index}-product`] = "Produk wajib diisi";
        }
        const qty = parseFloat(item.quantity || "0");
        const price = parseFloat(item.unitPrice || "0");
        if (qty <= 0) {
          newErrors[`item-${index}-quantity`] = "Kuantitas harus > 0";
        }
        if (price <= 0) {
          newErrors[`item-${index}-price`] = "Harga harus > 0";
        }
      });
    }

    setErrors(newErrors);
    setTouched({
      supplierId: true,
      invoiceDate: true,
      dueDate: true,
    });

    if (Object.keys(newErrors).length > 0) {
      console.log("❌ Validation errors:", newErrors);
    }

    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!validate()) {
      toast.error("Validasi Gagal", {
        description: "Mohon periksa kembali form Anda",
      });
      return;
    }

    try {
      const invoiceData: CreatePurchaseInvoiceRequest = {
        invoiceDate: formData.invoiceDate,
        dueDate: formData.dueDate,
        supplierId: formData.supplierId,
        purchaseOrderId: formData.purchaseOrderId || undefined,
        goodsReceiptId: formData.goodsReceiptId || undefined,
        // Only send header-level discount (line-level discounts are in each item)
        discountAmount: totals.headerDiscount > 0 ? totals.headerDiscount.toString() : undefined,
        taxRate: formData.taxPercentage,
        notes: formData.notes || undefined,
        // Non-Goods Costs (Biaya Tambahan)
        shippingCost: parseFloat(formData.shippingCost || "0") > 0 ? formData.shippingCost : undefined,
        handlingCost: parseFloat(formData.handlingCost || "0") > 0 ? formData.handlingCost : undefined,
        otherCost: parseFloat(formData.otherCost || "0") > 0 ? formData.otherCost : undefined,
        otherCostDescription: formData.otherCostDescription || undefined,
        items: items.map((item) => ({
          purchaseOrderItemId: item.purchaseOrderItemId || undefined,
          goodsReceiptItemId: item.goodsReceiptItemId || undefined,
          productId: item.productId,
          unitId: item.unitId, // UUID of the product unit
          quantity: item.quantity,
          unitPrice: item.unitPrice,
          discountAmount: item.discountAmount || undefined,
          discountPct: item.discountPercent || undefined,
          taxAmount: item.taxAmount || undefined,
          notes: undefined,
        })),
      };

      // Debug logging
      console.log("📦 Invoice Data being sent:", JSON.stringify(invoiceData, null, 2));

      const result = await createInvoice(invoiceData).unwrap();

      toast.success("Faktur Berhasil Dibuat", {
        description: `Faktur ${result.invoiceNumber} telah ditambahkan`,
      });

      if (onSuccess) {
        onSuccess(result.id);
      }
    } catch (error: any) {
      // Enhanced error logging for debugging
      console.error("❌ Create Invoice Error:", error);
      console.error("❌ Error Data:", error?.data);

      const errorMessage =
        error?.data?.details ||
        error?.data?.error?.message ||
        error?.data?.error ||
        error?.data?.message ||
        error?.message ||
        "Terjadi kesalahan pada server";

      toast.error("Gagal Membuat Faktur", {
        description: errorMessage,
      });
    }
  };

  // Helper function to check if item qty exceeds limit
  const isQtyExceedingLimit = (item: InvoiceItem): boolean => {
    const qty = parseFloat(item.quantity || "0");
    return qty > item.maxInvoiceableQty && item.maxInvoiceableQty > 0;
  };

  // Check if any item exceeds the limit
  const hasExceedingItems = items.some(isQtyExceedingLimit);

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Invoice Control Policy Info Banner */}
      <Alert className={invoiceControlPolicy === "RECEIVED" ? "border-green-200 bg-green-50/50" : "border-blue-200 bg-blue-50/50"}>
        <ShieldCheck className={`h-4 w-4 ${invoiceControlPolicy === "RECEIVED" ? "text-green-600" : "text-blue-600"}`} />
        <div className="ml-2">
          <div className="flex items-center gap-2">
            <span className={`font-medium ${invoiceControlPolicy === "RECEIVED" ? "text-green-900" : "text-blue-900"}`}>
              Kebijakan Faktur: {INVOICE_CONTROL_POLICY_LABELS[invoiceControlPolicy]}
            </span>
            {invoiceTolerancePct > 0 && (
              <Badge variant="outline" className="text-xs">
                Toleransi: {invoiceTolerancePct}%
              </Badge>
            )}
          </div>
          <p className={`text-sm mt-1 ${invoiceControlPolicy === "RECEIVED" ? "text-green-700" : "text-blue-700"}`}>
            {invoiceControlPolicy === "RECEIVED"
              ? "Faktur hanya dapat dibuat untuk qty yang sudah diterima (GRN). Pastikan barang sudah diterima sebelum membuat faktur."
              : "Faktur dapat dibuat berdasarkan qty yang dipesan di PO, tanpa harus menunggu penerimaan barang."
            }
            {invoiceTolerancePct > 0 && ` Toleransi over-invoice: ${invoiceTolerancePct}%.`}
          </p>
        </div>
      </Alert>

      {/* Invoice Number - Auto-generated by backend based on company format settings */}
      <div className="rounded-md bg-muted/50 p-3 border border-border">
        <p className="text-sm text-muted-foreground">
          <FileText className="h-4 w-4 inline mr-1" />
          Nomor faktur akan di-generate otomatis oleh sistem berdasarkan format yang dikonfigurasi di Company Settings
        </p>
      </div>

      {/* Warning if any item exceeds limit */}
      {hasExceedingItems && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>
            <span className="font-medium">Peringatan:</span> Beberapa item memiliki qty yang melebihi batas maksimal.
            Faktur mungkin akan ditolak oleh sistem. Silakan periksa dan sesuaikan qty item yang ditandai.
          </AlertDescription>
        </Alert>
      )}

      {/* Invoice Header */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Informasi Faktur
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid gap-6 sm:grid-cols-2">
            {/* Supplier Selection */}
            <div className="space-y-2">
              <Label htmlFor="supplier" className="text-sm font-medium">
                <div className="flex items-center gap-2">
                  <Building2 className="h-4 w-4" />
                  Supplier <span className="text-destructive">*</span>
                </div>
              </Label>
              <Select
                value={formData.supplierId}
                onValueChange={(value) => {
                  handleChange("supplierId", value);
                  // Clear PO and GRN selection when supplier changes
                  if (formData.purchaseOrderId) {
                    handleChange("purchaseOrderId", "");
                    handleChange("purchaseOrderNumber", "");
                  }
                  if (formData.goodsReceiptId) {
                    handleChange("goodsReceiptId", "");
                    handleChange("goodsReceiptNumber", "");
                  }
                  // Clear items when supplier changes
                  setItems([]);
                }}
              >
                <SelectTrigger
                  className={`w-full ${
                    errors.supplierId && touched.supplierId
                      ? "border-destructive"
                      : ""
                  }`}
                >
                  <SelectValue
                    placeholder={
                      isLoadingSuppliers
                        ? "Memuat supplier..."
                        : suppliers.length === 0
                        ? "Tidak ada supplier aktif"
                        : "Pilih supplier..."
                    }
                  />
                </SelectTrigger>
                <SelectContent>
                  {suppliers.map((supplier) => (
                    <SelectItem key={supplier.id} value={supplier.id}>
                      {supplier.code} - {supplier.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {errors.supplierId && touched.supplierId && (
                <p className="flex items-center gap-1 text-sm text-destructive">
                  <AlertCircle className="h-3 w-3" />
                  {errors.supplierId}
                </p>
              )}
            </div>

            {/* Purchase Order Reference */}
            <div className="space-y-2">
              <Label htmlFor="purchaseOrder" className="text-sm font-medium">
                Referensi PO <span className="text-destructive">*</span>
              </Label>
              <Select
                value={formData.purchaseOrderId}
                onValueChange={(value) => {
                  const selectedPO = purchaseOrders.find(po => po.id === value);
                  handleChange("purchaseOrderId", value);
                  if (selectedPO) {
                    handleChange("purchaseOrderNumber", selectedPO.poNumber);
                  }
                  // Clear GRN and items when PO changes
                  if (formData.goodsReceiptId) {
                    handleChange("goodsReceiptId", "");
                    handleChange("goodsReceiptNumber", "");
                  }
                  setItems([]);
                }}
                disabled={!formData.supplierId}
              >
                <SelectTrigger className="w-full">
                  <SelectValue
                    placeholder={
                      !formData.supplierId
                        ? "Pilih supplier terlebih dahulu"
                        : isLoadingPOs
                        ? "Memuat PO..."
                        : purchaseOrders.length === 0
                        ? "Tidak ada PO yang bisa diinvoice"
                        : "Pilih PO..."
                    }
                  />
                </SelectTrigger>
                <SelectContent>
                  {purchaseOrders.map((po) => (
                    <SelectItem key={po.id} value={po.id} textValue={po.poNumber}>
                      <div className="flex items-center gap-2">
                        <span>{po.poNumber}</span>
                        <Badge
                          variant="secondary"
                          className={`text-xs ${PURCHASE_ORDER_STATUS_COLORS[po.status as PurchaseOrderStatus]}`}
                        >
                          {PURCHASE_ORDER_STATUS_LABELS[po.status as PurchaseOrderStatus]}
                        </Badge>
                        <span className="text-muted-foreground">
                          {new Date(po.poDate).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })}
                        </span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">
                Menampilkan PO dengan status: Dikonfirmasi, Selesai, atau Ditutup Sebagian
              </p>
            </div>

            {/* Goods Receipt Reference - Full Width */}
            <div className="space-y-2 sm:col-span-2">
              <Label htmlFor="goodsReceipt" className="text-sm font-medium">
                Referensi Penerimaan Barang (GRN) <span className="text-destructive">*</span>
              </Label>
              <TooltipProvider>
                <Select
                  value={formData.goodsReceiptId}
                  onValueChange={(value) => {
                    const selectedGR = goodsReceipts.find(gr => gr.id === value);
                    handleChange("goodsReceiptId", value);
                    if (selectedGR) {
                      handleChange("goodsReceiptNumber", selectedGR.grnNumber);
                    }
                    // Clear items when GRN changes - will be repopulated by useEffect
                    setItems([]);
                  }}
                  disabled={!formData.purchaseOrderId}
                >
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Pilih GRN..." />
                  </SelectTrigger>
                  <SelectContent>
                    {goodsReceipts.map((gr) => {
                      // Use invoice status from the GRN list data (calculated by backend)
                      const invoiceStatusBadge = getGRNBadgeFromList(gr);
                      return (
                        <SelectItem
                          key={gr.id}
                          value={gr.id}
                          textValue={gr.grnNumber}
                        >
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className={invoiceStatusBadge.disabled ? "text-muted-foreground" : ""}>
                              {gr.grnNumber}
                            </span>
                            {/* GRN Status Badge */}
                            <Badge
                              variant="secondary"
                              className={gr.status === "ACCEPTED" ? "bg-green-100 text-green-800" : "bg-orange-100 text-orange-800"}
                            >
                              {gr.status === "ACCEPTED" ? "Diterima Penuh" : "Diterima Sebagian"}
                            </Badge>
                            {/* Invoice Status Badge from backend data */}
                            {invoiceStatusBadge && (
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <Badge
                                    variant="outline"
                                    className={`${invoiceStatusBadge.color} flex items-center gap-1`}
                                  >
                                    <invoiceStatusBadge.icon className="h-3 w-3" />
                                    {invoiceStatusBadge.label}
                                  </Badge>
                                </TooltipTrigger>
                                <TooltipContent>
                                  <p>{invoiceStatusBadge.tooltip}</p>
                                </TooltipContent>
                              </Tooltip>
                            )}
                            <span className="text-muted-foreground text-xs">
                              {new Date(gr.grnDate).toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })}
                            </span>
                            <span className="text-xs text-muted-foreground">
                              ({gr.itemCount} item)
                            </span>
                          </div>
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>
              </TooltipProvider>
              {errors.goodsReceiptId && (
                <p className="flex items-center gap-1 text-sm text-destructive">
                  <AlertCircle className="h-3 w-3" />
                  {errors.goodsReceiptId}
                </p>
              )}
              {/* Alert when selected GRN is fully invoiced */}
              {isSelectedGRNFullyInvoiced && (
                <Alert variant="destructive" className="mt-2">
                  <CheckCircle2 className="h-4 w-4" />
                  <AlertDescription>
                    Semua item dari GRN ini sudah sepenuhnya di-invoice. Tidak dapat membuat faktur baru dari GRN ini.
                  </AlertDescription>
                </Alert>
              )}
              {!errors.goodsReceiptId && !isSelectedGRNFullyInvoiced && (
                <p className="text-xs text-muted-foreground">
                  {/* Show different message based on GRN invoice status */}
                  {goodsReceipts.some(gr => gr.invoiceStatus === "PARTIAL")
                    ? "Beberapa item mungkin sudah di-invoice. Hanya item dengan sisa qty yang akan ditambahkan."
                    : "Pilih GRN untuk otomatis mengisi items berdasarkan barang yang sudah diterima"
                  }
                </p>
              )}
            </div>

            {/* Invoice Date */}
            <div className="space-y-2">
              <Label htmlFor="invoiceDate" className="text-sm font-medium">
                Tanggal Faktur <span className="text-destructive">*</span>
              </Label>
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-muted-foreground" />
                <Input
                  id="invoiceDate"
                  type="date"
                  value={formData.invoiceDate}
                  onChange={(e) => handleChange("invoiceDate", e.target.value)}
                  onBlur={() => handleBlur("invoiceDate")}
                  className={
                    errors.invoiceDate && touched.invoiceDate
                      ? "border-destructive"
                      : ""
                  }
                />
              </div>
              {errors.invoiceDate && touched.invoiceDate && (
                <p className="flex items-center gap-1 text-sm text-destructive">
                  <AlertCircle className="h-3 w-3" />
                  {errors.invoiceDate}
                </p>
              )}
            </div>

            {/* Due Date */}
            <div className="space-y-2">
              <Label htmlFor="dueDate" className="text-sm font-medium">
                Jatuh Tempo <span className="text-destructive">*</span>
              </Label>
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-muted-foreground" />
                <Input
                  id="dueDate"
                  type="date"
                  value={formData.dueDate}
                  onChange={(e) => handleChange("dueDate", e.target.value)}
                  onBlur={() => handleBlur("dueDate")}
                  className={
                    errors.dueDate && touched.dueDate
                      ? "border-destructive"
                      : ""
                  }
                />
              </div>
              {errors.dueDate && touched.dueDate && (
                <p className="flex items-center gap-1 text-sm text-destructive">
                  <AlertCircle className="h-3 w-3" />
                  {errors.dueDate}
                </p>
              )}
            </div>

            {/* Header Discount */}
            <div className="space-y-2">
              <Label htmlFor="headerDiscount" className="text-sm font-medium">
                Diskon Faktur (Rp)
              </Label>
              <div className="flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-muted-foreground" />
                <Input
                  id="headerDiscount"
                  type="number"
                  min="0"
                  step="0.01"
                  value={formData.headerDiscountAmount}
                  onChange={(e) => handleChange("headerDiscountAmount", e.target.value)}
                  placeholder="0"
                  className="font-mono"
                />
              </div>
              <p className="text-xs text-muted-foreground">
                Diskon tambahan pada level faktur (selain diskon per item)
              </p>
            </div>

            {/* Notes */}
            <div className="space-y-2 sm:col-span-2">
              <Label htmlFor="notes" className="text-sm font-medium">
                Catatan
              </Label>
              <Textarea
                id="notes"
                value={formData.notes}
                onChange={(e) => handleChange("notes", e.target.value)}
                placeholder="Catatan tambahan untuk faktur ini..."
                rows={3}
                className="resize-none"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Additional Costs (Non-Goods Costs) */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ReceiptText className="h-5 w-5" />
            Biaya Tambahan
          </CardTitle>
          <p className="text-sm text-muted-foreground">
            Biaya non-barang seperti ongkir, handling, dan biaya lainnya
          </p>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 sm:grid-cols-3">
            {/* Shipping Cost */}
            <div className="space-y-2">
              <Label htmlFor="shippingCost" className="text-sm font-medium">
                <div className="flex items-center gap-2">
                  <Truck className="h-4 w-4" />
                  Biaya Pengiriman
                </div>
              </Label>
              <Input
                id="shippingCost"
                type="number"
                min="0"
                step="1000"
                value={formData.shippingCost}
                onChange={(e) => handleChange("shippingCost", e.target.value)}
                placeholder="0"
                className="text-right"
              />
              <p className="text-xs text-muted-foreground">Ongkos kirim dari supplier</p>
            </div>

            {/* Handling Cost */}
            <div className="space-y-2">
              <Label htmlFor="handlingCost" className="text-sm font-medium">
                <div className="flex items-center gap-2">
                  <HandCoins className="h-4 w-4" />
                  Biaya Handling
                </div>
              </Label>
              <Input
                id="handlingCost"
                type="number"
                min="0"
                step="1000"
                value={formData.handlingCost}
                onChange={(e) => handleChange("handlingCost", e.target.value)}
                placeholder="0"
                className="text-right"
              />
              <p className="text-xs text-muted-foreground">Biaya bongkar muat</p>
            </div>

            {/* Other Cost */}
            <div className="space-y-2">
              <Label htmlFor="otherCost" className="text-sm font-medium">
                <div className="flex items-center gap-2">
                  <DollarSign className="h-4 w-4" />
                  Biaya Lain-lain
                </div>
              </Label>
              <Input
                id="otherCost"
                type="number"
                min="0"
                step="1000"
                value={formData.otherCost}
                onChange={(e) => handleChange("otherCost", e.target.value)}
                placeholder="0"
                className="text-right"
              />
              <p className="text-xs text-muted-foreground">Biaya tambahan lainnya</p>
            </div>

            {/* Other Cost Description - Only show if other cost > 0 */}
            {parseFloat(formData.otherCost || "0") > 0 && (
              <div className="space-y-2 sm:col-span-3">
                <Label htmlFor="otherCostDescription" className="text-sm font-medium">
                  Keterangan Biaya Lain-lain
                </Label>
                <Input
                  id="otherCostDescription"
                  value={formData.otherCostDescription}
                  onChange={(e) => handleChange("otherCostDescription", e.target.value)}
                  placeholder="Jelaskan biaya lain-lain..."
                />
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Invoice Items */}
      <Card className="border-2">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="h-5 w-5" />
            Item Faktur
          </CardTitle>
          <p className="text-sm text-muted-foreground">
            Items otomatis terisi dari Penerimaan Barang (GRN) yang dipilih
          </p>
        </CardHeader>
        <CardContent>
          {errors.items && (
            <Alert variant="destructive" className="mb-4">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>{errors.items}</AlertDescription>
            </Alert>
          )}

          {items.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <Package className="mx-auto h-12 w-12 mb-4 opacity-50" />
              <p className="font-medium">Belum ada item dalam faktur</p>
              <p className="text-sm mt-1">
                {!formData.goodsReceiptId
                  ? "Pilih Penerimaan Barang (GRN) untuk mengisi items secara otomatis"
                  : "Items akan terisi otomatis dari GRN yang dipilih"
                }
              </p>
            </div>
          ) : (
            <div className="rounded-md border overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-[250px]">Produk</TableHead>
                    <TableHead className="w-[100px]">Kuantitas</TableHead>
                    <TableHead className="w-[120px] text-right">Harga Satuan</TableHead>
                    <TableHead className="w-[120px] text-right">Diskon</TableHead>
                    <TableHead className="w-[120px] text-right">PPN</TableHead>
                    <TableHead className="w-[120px] text-right">Total</TableHead>
                    <TableHead className="w-[50px]"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {items.map((item, index) => {
                    const exceeds = isQtyExceedingLimit(item);
                    return (
                    <TableRow key={item.id} className={exceeds ? "bg-red-50" : ""}>
                      <TableCell>
                        <div className="space-y-1">
                          <Input
                            value={item.productName}
                            onChange={(e) =>
                              handleItemChange(item.id, "productName", e.target.value)
                            }
                            placeholder="Nama produk"
                            className="h-8"
                          />
                          <p className="text-xs text-muted-foreground">{item.productCode}</p>
                        </div>
                        {errors[`item-${index}-product`] && (
                          <p className="text-xs text-destructive mt-1">
                            {errors[`item-${index}-product`]}
                          </p>
                        )}
                      </TableCell>
                      <TableCell>
                        <div className="space-y-1">
                          <div className="flex items-center gap-1">
                            <Input
                              type="number"
                              value={item.quantity}
                              onChange={(e) =>
                                handleItemChange(item.id, "quantity", e.target.value)
                              }
                              className={`h-8 w-16 ${exceeds ? "border-destructive" : ""}`}
                            />
                            <span className="text-sm text-muted-foreground whitespace-nowrap">
                              {item.unitName}
                            </span>
                            {exceeds && (
                              <AlertTriangle className="h-4 w-4 text-destructive flex-shrink-0" />
                            )}
                          </div>
                          {item.maxInvoiceableQty > 0 && (
                            <p className={`text-xs ${exceeds ? "text-destructive font-medium" : "text-muted-foreground"}`}>
                              Max: {item.maxInvoiceableQty.toFixed(2)}
                              {invoiceControlPolicy === "RECEIVED" ? " (diterima)" : " (dipesan)"}
                            </p>
                          )}
                        </div>
                      </TableCell>
                      <TableCell className="text-right">
                        <Input
                          type="number"
                          value={item.unitPrice}
                          onChange={(e) =>
                            handleItemChange(item.id, "unitPrice", e.target.value)
                          }
                          className="h-8 text-right"
                        />
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="space-y-1">
                          <div className="font-mono text-sm">
                            {formatCurrency(item.discountAmount)}
                          </div>
                          <div className="flex items-center justify-end gap-1">
                            <Input
                              type="number"
                              value={item.discountPercent}
                              onChange={(e) =>
                                handleItemChange(item.id, "discountPercent", e.target.value)
                              }
                              className="h-6 w-14 text-right text-xs"
                            />
                            <span className="text-xs text-muted-foreground">%</span>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="space-y-1">
                          <div className="font-mono text-sm">
                            {formatCurrency(item.taxAmount)}
                          </div>
                          <div className="flex items-center justify-end gap-1">
                            <Input
                              type="number"
                              value={item.taxPercent}
                              onChange={(e) =>
                                handleItemChange(item.id, "taxPercent", e.target.value)
                              }
                              className="h-6 w-14 text-right text-xs"
                            />
                            <span className="text-xs text-muted-foreground">%</span>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm font-medium text-primary">
                        {formatCurrency(item.totalAmount)}
                      </TableCell>
                      <TableCell>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() => handleRemoveItem(item.id)}
                          disabled={isLoading}
                          className="h-8 w-8 p-0"
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </TableCell>
                    </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Financial Summary */}
      {items.length > 0 && (
        <Card className="border-2">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <DollarSign className="h-5 w-5" />
              Ringkasan Keuangan
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Subtotal */}
            <div className="flex items-center justify-between">
              <p className="text-sm font-medium text-muted-foreground">Subtotal</p>
              <p className="font-mono font-semibold">
                {formatCurrency(totals.subtotal)}
              </p>
            </div>

            <Separator />

            {/* Diskon Item (dari masing-masing item) */}
            {totals.lineDiscount > 0 && (
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-muted-foreground">Diskon Item</p>
                <p className="font-mono font-semibold text-green-600">
                  - {formatCurrency(totals.lineDiscount)}
                </p>
              </div>
            )}

            {/* Diskon Faktur (header-level discount) */}
            {totals.headerDiscount > 0 && (
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-muted-foreground">Diskon Faktur</p>
                <p className="font-mono font-semibold text-green-600">
                  - {formatCurrency(totals.headerDiscount)}
                </p>
              </div>
            )}

            {/* Separator setelah diskon jika ada */}
            {totals.totalDiscount > 0 && <Separator />}

            {/* PPN */}
            {totals.totalTax > 0 && (
              <>
                <div className="flex items-center justify-between">
                  <p className="text-sm font-medium text-muted-foreground">
                    PPN ({formData.taxPercentage || 0}%)
                  </p>
                  <p className="font-mono font-semibold">
                    {formatCurrency(totals.totalTax)}
                  </p>
                </div>
                <Separator />
              </>
            )}

            {/* Non-Goods Costs Section */}
            {totals.totalNonGoodsCost > 0 && (
              <>
                <div className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  Biaya Tambahan
                </div>
                {totals.shippingCost > 0 && (
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-medium text-muted-foreground flex items-center gap-1">
                      <Truck className="h-3 w-3" />
                      Biaya Pengiriman
                    </p>
                    <p className="font-mono font-semibold">
                      {formatCurrency(totals.shippingCost)}
                    </p>
                  </div>
                )}
                {totals.handlingCost > 0 && (
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-medium text-muted-foreground flex items-center gap-1">
                      <HandCoins className="h-3 w-3" />
                      Biaya Handling
                    </p>
                    <p className="font-mono font-semibold">
                      {formatCurrency(totals.handlingCost)}
                    </p>
                  </div>
                )}
                {totals.otherCost > 0 && (
                  <div className="flex items-center justify-between">
                    <p className="text-sm font-medium text-muted-foreground flex items-center gap-1">
                      <DollarSign className="h-3 w-3" />
                      Biaya Lain-lain
                    </p>
                    <p className="font-mono font-semibold">
                      {formatCurrency(totals.otherCost)}
                    </p>
                  </div>
                )}
                <Separator />
              </>
            )}

            {/* Total */}
            <div className="flex items-center justify-between rounded-lg bg-muted/50 p-4">
              <p className="text-base font-bold">Total</p>
              <p className="text-2xl font-bold text-blue-600">
                {formatCurrency(totals.total)}
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Form Actions */}
      <div className="flex justify-end gap-3 pt-2">
        {onCancel && (
          <Button
            type="button"
            variant="outline"
            onClick={onCancel}
            disabled={isLoading}
            size="lg"
          >
            Batal
          </Button>
        )}
        <Button
          type="submit"
          disabled={isLoading || items.length === 0}
          size="lg"
          className="min-w-[150px]"
        >
          {isLoading ? (
            <>
              <span className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
              Menyimpan...
            </>
          ) : (
            <>
              <Save className="mr-2 h-4 w-4" />
              Simpan Faktur
            </>
          )}
        </Button>
      </div>
    </form>
  );
}
