// Package examples - Phase 1 usage examples
// This file demonstrates how to use the Phase 1 GORM models
package examples

import (
	"backend/db"
	"backend/models"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/shopspring/decimal"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// ExampleSetupDatabase shows how to initialize database and run migration
func ExampleSetupDatabase() {
	// Get DATABASE_URL from environment variable
	// Example: postgresql://user:password@localhost:5432/erp_db?sslmode=disable
	databaseURL := os.Getenv("DATABASE_URL")
	if databaseURL == "" {
		log.Fatal("DATABASE_URL environment variable is required")
	}

	// Open database connection (PostgreSQL)
	database, err := gorm.Open(postgres.Open(databaseURL), &gorm.Config{})
	if err != nil {
		log.Fatal("Failed to connect to database:", err)
	}

	// Run Phase 1 migration
	if err := db.AutoMigratePhase1(database); err != nil {
		log.Fatal("Migration failed:", err)
	}

	fmt.Println("✅ Database setup complete!")
}

// ExampleCreateUser shows how to create a new user
func ExampleCreateUser(database *gorm.DB) {
	user := &models.User{
		Email:         "john.doe@company.com",
		Username:      "johndoe",
		PasswordHash:  "$2a$10$hashedPasswordHere", // Should be bcrypt hashed
		FullName:      "John Doe",
		IsSystemAdmin: false,
		IsActive:      true,
	}

	// CUID will be auto-generated by BeforeCreate hook
	result := database.Create(user)
	if result.Error != nil {
		log.Printf("Error creating user: %v", result.Error)
		return
	}

	fmt.Printf("✅ User created with ID: %s\n", user.ID)
}

// ExampleCreateCompany shows how to create a company with Indonesian tax setup
func ExampleCreateCompany(database *gorm.DB) {
	npwp := "01.234.567.8-901.234"
	company := &models.Company{
		// Legal Entity
		Name:       "CV Maju Bersama",
		LegalName:  "CV Maju Bersama Sejahtera",
		EntityType: "CV",

		// Address
		Address:  "Jl. Sudirman No. 123, Kebayoran Baru",
		City:     "Jakarta Selatan",
		Province: "DKI Jakarta",
		Country:  "Indonesia",

		// Contact
		Phone: "021-7654321",
		Email: "info@majubersama.co.id",

		// Indonesian Tax Compliance
		NPWP:    &npwp,
		IsPKP:   true,
		PPNRate: decimal.NewFromFloat(11.0), // 11% PPN

		// System Settings
		Currency: "IDR",
		Timezone: "Asia/Jakarta",
		Locale:   "id-ID",
	}

	result := database.Create(company)
	if result.Error != nil {
		log.Printf("Error creating company: %v", result.Error)
		return
	}

	fmt.Printf("✅ Company created with ID: %s\n", company.ID)
}

// ExampleCreateTenantWithTrial shows how to create a tenant with 14-day trial
// Updated for PHASE 3: Multi-company architecture
func ExampleCreateTenantWithTrial(database *gorm.DB) {
	trialEnds := time.Now().AddDate(0, 0, 14) // 14 days from now

	tenant := &models.Tenant{
		Name:        "PT Distribusi Nusantara",
		Subdomain:   "distribusi-nusantara",
		Status:      models.TenantStatusTrial,
		TrialEndsAt: &trialEnds,
	}

	result := database.Create(tenant)
	if result.Error != nil {
		log.Printf("Error creating tenant: %v", result.Error)
		return
	}

	fmt.Printf("✅ Tenant created with ID: %s (Trial until: %s)\n",
		tenant.ID, trialEnds.Format("2006-01-02"))
}

// ExampleCreateSubscription shows how to create a subscription with custom pricing
func ExampleCreateSubscription(database *gorm.DB) {
	now := time.Now()
	nextMonth := now.AddDate(0, 1, 0)

	subscription := &models.Subscription{
		Price:              decimal.NewFromFloat(350000), // Custom price Rp 350,000
		BillingCycle:       "MONTHLY",
		Status:             models.SubscriptionStatusActive,
		CurrentPeriodStart: now,
		CurrentPeriodEnd:   nextMonth,
		NextBillingDate:    nextMonth,
		AutoRenew:          true,
	}

	result := database.Create(subscription)
	if result.Error != nil {
		log.Printf("Error creating subscription: %v", result.Error)
		return
	}

	fmt.Printf("✅ Subscription created with ID: %s (Price: Rp %s/month)\n",
		subscription.ID, subscription.Price.StringFixed(0))
}

// ExampleLinkTenantToSubscription shows how to upgrade tenant from trial to paid
func ExampleLinkTenantToSubscription(database *gorm.DB, tenantID, subscriptionID string) {
	result := database.Model(&models.Tenant{}).
		Where("id = ?", tenantID).
		Updates(map[string]interface{}{
			"subscription_id": subscriptionID,
			"status":          models.TenantStatusActive,
		})

	if result.Error != nil {
		log.Printf("Error linking subscription: %v", result.Error)
		return
	}

	fmt.Println("✅ Tenant upgraded to paid subscription")
}

// ExampleAssignUserToTenant shows how to give a user access to a tenant with specific role
func ExampleAssignUserToTenant(database *gorm.DB, userID, tenantID string) {
	userTenant := &models.UserTenant{
		UserID:   userID,
		TenantID: tenantID,
		Role:     models.UserRoleOwner, // OWNER, ADMIN, FINANCE, SALES, WAREHOUSE, STAFF
		IsActive: true,
	}

	result := database.Create(userTenant)
	if result.Error != nil {
		log.Printf("Error assigning user to tenant: %v", result.Error)
		return
	}

	fmt.Printf("✅ User assigned to tenant with role: %s\n", userTenant.Role)
}

// ExampleQueryUserTenants shows how to get all tenants a user has access to
func ExampleQueryUserTenants(database *gorm.DB, userID string) {
	var userTenants []models.UserTenant

	result := database.
		Preload("Tenant").
		Preload("Tenant.Company").
		Where("user_id = ? AND is_active = ?", userID, true).
		Find(&userTenants)

	if result.Error != nil {
		log.Printf("Error querying user tenants: %v", result.Error)
		return
	}

	fmt.Printf("✅ User has access to %d tenant(s):\n", len(userTenants))
	for _, ut := range userTenants {
		fmt.Printf("   - Tenant: %s (Role: %s, Status: %s)\n",
			ut.Tenant.Name,
			ut.Role,
			ut.Tenant.Status)
	}
}

// ExampleAddCompanyBank shows how to add a bank account to a company
func ExampleAddCompanyBank(database *gorm.DB, companyID string) {
	bank := &models.CompanyBank{
		CompanyID:     companyID,
		BankName:      "BCA",
		AccountNumber: "1234567890",
		AccountName:   "CV Maju Bersama",
		BranchName:    stringPtr("KCP Jakarta Sudirman"),
		IsPrimary:     true, // Primary bank for invoices
	}

	result := database.Create(bank)
	if result.Error != nil {
		log.Printf("Error adding bank account: %v", result.Error)
		return
	}

	fmt.Printf("✅ Bank account added: %s - %s\n", bank.BankName, bank.AccountNumber)
}

// ExampleRecordSubscriptionPayment shows how to record a subscription payment
func ExampleRecordSubscriptionPayment(database *gorm.DB, subscriptionID string) {
	now := time.Now()
	periodEnd := now.AddDate(0, 1, 0)
	invoiceNum := "INV-SUB-001/12/2025"

	payment := &models.SubscriptionPayment{
		SubscriptionID: subscriptionID,
		Amount:         decimal.NewFromFloat(300000),
		PaymentDate:    now,
		PaymentMethod:  "TRANSFER",
		Status:         models.SubscriptionPaymentStatusPaid,
		Reference:      stringPtr("TRF-20251215-001"),
		InvoiceNumber:  &invoiceNum,
		PeriodStart:    now,
		PeriodEnd:      periodEnd,
		PaidAt:         &now,
	}

	result := database.Create(payment)
	if result.Error != nil {
		log.Printf("Error recording payment: %v", result.Error)
		return
	}

	fmt.Printf("✅ Payment recorded: Rp %s (Invoice: %s)\n",
		payment.Amount.StringFixed(0),
		*payment.InvoiceNumber)
}

// ExampleFullOnboardingFlow demonstrates complete company onboarding
func ExampleFullOnboardingFlow(database *gorm.DB) {
	fmt.Println("🚀 Starting complete onboarding flow...")

	// 1. Create Company
	npwp := "12.345.678.9-012.345"
	company := &models.Company{
		Name:       "PT Distribusi Sejahtera",
		LegalName:  "PT Distribusi Sejahtera Indonesia",
		EntityType: "PT",
		Address:    "Jl. Gatot Subroto No. 456",
		City:       "Jakarta Pusat",
		Province:   "DKI Jakarta",
		Phone:      "021-5551234",
		Email:      "info@distrisejahtera.com",
		NPWP:       &npwp,
		IsPKP:      true,
		PPNRate:    decimal.NewFromFloat(11.0),
	}
	database.Create(company)
	fmt.Printf("1️⃣ Company created: %s\n", company.Name)

	// 2. Create Tenant with Trial
	trialEnds := time.Now().AddDate(0, 0, 14)
	tenant := &models.Tenant{
		Name:        "PT Distribusi Sejahtera",
		Subdomain:   "distribusi-sejahtera",
		Status:      models.TenantStatusTrial,
		TrialEndsAt: &trialEnds,
	}
	database.Create(tenant)
	// Link company to tenant
	company.TenantID = tenant.ID
	database.Save(company)
	fmt.Printf("2️⃣ Tenant created (Trial until: %s)\n", trialEnds.Format("2006-01-02"))

	// 3. Create Owner User
	owner := &models.User{
		Email:        "owner@distrisejahtera.com",
		Username:     "owner_distri",
		PasswordHash: "$2a$10$hashedPassword",
		FullName:     "Budi Santoso",
		IsActive:     true,
	}
	database.Create(owner)
	fmt.Printf("3️⃣ Owner user created: %s\n", owner.FullName)

	// 4. Assign Owner to Tenant
	userTenant := &models.UserTenant{
		UserID:   owner.ID,
		TenantID: tenant.ID,
		Role:     models.UserRoleOwner,
		IsActive: true,
	}
	database.Create(userTenant)
	fmt.Printf("4️⃣ Owner assigned to tenant with OWNER role\n")

	// 5. Add Primary Bank Account
	bank := &models.CompanyBank{
		CompanyID:     company.ID,
		BankName:      "Mandiri",
		AccountNumber: "1370012345678",
		AccountName:   company.LegalName,
		IsPrimary:     true,
	}
	database.Create(bank)
	fmt.Printf("5️⃣ Bank account added: %s\n", bank.BankName)

	// 6. Create Subscription (when trial converts)
	subscription := &models.Subscription{
		Price:              decimal.NewFromFloat(300000),
		BillingCycle:       "MONTHLY",
		Status:             models.SubscriptionStatusActive,
		CurrentPeriodStart: time.Now(),
		CurrentPeriodEnd:   time.Now().AddDate(0, 1, 0),
		NextBillingDate:    time.Now().AddDate(0, 1, 0),
		AutoRenew:          true,
	}
	database.Create(subscription)
	fmt.Printf("6️⃣ Subscription created: Rp %s/month\n",
		subscription.Price.StringFixed(0))

	// 7. Link Tenant to Subscription
	database.Model(&tenant).Updates(map[string]interface{}{
		"subscription_id": subscription.ID,
		"status":          models.TenantStatusActive,
	})
	fmt.Printf("7️⃣ Tenant upgraded to ACTIVE status\n")

	fmt.Println("\n✅ Onboarding complete! Company is ready to use the ERP system.")
}

// Helper function to create string pointer
func stringPtr(s string) *string {
	return &s
}
