/**
 * Invoice Types
 *
 * TypeScript type definitions for sales invoice management.
 * Based on backend models/invoice.go and internal/dto/invoice_dto.go
 */

/**
 * Invoice
 * Customer sales invoice entity
 */
export interface Invoice {
  id: string;
  invoiceNumber: string;
  invoiceDate: string; // ISO date string
  dueDate: string; // ISO date string
  customerId: string;
  customerName: string;
  customerCode?: string | null;
  salesOrderId?: string | null;
  soNumber?: string | null;
  deliveryId?: string | null;
  deliveryNumber?: string | null;
  subtotal: string; // decimal as string
  discountAmount: string; // decimal as string
  taxAmount: string; // decimal as string
  totalAmount: string; // decimal as string
  paidAmount: string; // decimal as string
  remainingAmount: string; // decimal as string (calculated)
  paymentStatus: PaymentStatus;
  notes?: string | null;
  fakturPajakNo?: string | null; // Tax invoice number
  fakturPajakDate?: string | null; // ISO date string
  createdAt: string;
  updatedAt: string;
  items?: InvoiceItem[];
  payments?: InvoicePayment[];
}

/**
 * Invoice Item
 * Line items in sales invoice
 */
export interface InvoiceItem {
  id: string;
  invoiceId: string;
  salesOrderItemId?: string | null;
  deliveryItemId?: string | null;
  productId: string;
  productCode: string;
  productName: string;
  productUnitId?: string | null;
  unitName: string;
  quantity: string; // decimal as string
  unitPrice: string; // decimal as string
  discountPct: string; // decimal as string
  discountAmt: string; // decimal as string
  subtotal: string; // decimal as string
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Invoice Payment
 * Payment transaction against invoice
 */
export interface InvoicePayment {
  id: string;
  paymentNumber: string;
  paymentDate: string; // ISO date string
  amount: string; // decimal as string
  paymentMethod: PaymentMethod;
  reference?: string | null;
  bankAccountId?: string | null;
  notes?: string | null;
  receivedBy?: string | null;
  receivedAt?: string | null; // ISO datetime string
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// API Request DTOs
// ============================================================================

/**
 * Create Invoice Request
 */
export interface CreateInvoiceRequest {
  invoiceDate: string; // ISO date string
  dueDate: string; // ISO date string
  customerId: string;
  salesOrderId?: string;
  deliveryId?: string;
  discountAmount?: string; // decimal as string
  taxAmount?: string; // decimal as string
  notes?: string;
  fakturPajakNo?: string;
  fakturPajakDate?: string; // ISO date string
  items: CreateInvoiceItemRequest[];
}

/**
 * Create Invoice Item Request
 */
export interface CreateInvoiceItemRequest {
  salesOrderItemId?: string;
  deliveryItemId?: string;
  productId: string;
  productUnitId?: string;
  quantity: string; // decimal as string
  unitPrice: string; // decimal as string
  discountPct?: string; // decimal as string
  discountAmt?: string; // decimal as string
  notes?: string;
}

/**
 * Update Invoice Request
 * Partial update - all fields optional
 */
export interface UpdateInvoiceRequest {
  invoiceDate?: string;
  dueDate?: string;
  customerId?: string;
  discountAmount?: string;
  taxAmount?: string;
  notes?: string;
  fakturPajakNo?: string;
  fakturPajakDate?: string;
}

/**
 * Record Payment Request (Sales Invoice)
 * Payment number is auto-generated by the system
 */
export interface RecordPaymentRequest {
  paymentDate: string; // ISO date string
  amount: string; // decimal as string
  paymentMethod: string; // PaymentMethod value
  reference?: string;
  bankAccountId?: string;
  notes?: string;
}

/**
 * Invoice Filters
 * Query parameters for listing invoices
 */
export interface InvoiceFilters {
  search?: string; // search in invoice number, customer name
  customerId?: string; // filter by customer
  paymentStatus?: PaymentStatus; // filter by payment status
  dateFrom?: string; // ISO date string - invoice date range start
  dateTo?: string; // ISO date string - invoice date range end
  dueDateFrom?: string; // ISO date string - due date range start
  dueDateTo?: string; // ISO date string - due date range end
  page?: number;
  pageSize?: number;
  sortBy?: "invoiceNumber" | "invoiceDate" | "dueDate" | "totalAmount" | "customerName" | "createdAt";
  sortOrder?: "asc" | "desc";
}

// ============================================================================
// API Response DTOs
// ============================================================================

/**
 * Invoice Response
 * Complete invoice information from API
 */
export interface InvoiceResponse extends Invoice {}

/**
 * Invoice List Response
 * Paginated list of invoices
 */
export interface InvoiceListResponse {
  success: boolean;
  data: InvoiceResponse[];
  pagination: PaginationInfo;
}

/**
 * Pagination Information
 */
export interface PaginationInfo {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

// ============================================================================
// Enums & Constants
// ============================================================================

/**
 * Payment Status
 */
export type PaymentStatus = "UNPAID" | "PARTIAL" | "PAID" | "OVERDUE";

export const PAYMENT_STATUS_LABELS: Record<PaymentStatus, string> = {
  UNPAID: "Belum Dibayar",
  PARTIAL: "Dibayar Sebagian",
  PAID: "Lunas",
  OVERDUE: "Terlambat",
};

export const PAYMENT_STATUS_COLORS: Record<PaymentStatus, string> = {
  UNPAID: "bg-red-500",
  PARTIAL: "bg-yellow-500",
  PAID: "bg-green-500",
  OVERDUE: "bg-orange-500",
};

/**
 * Payment Method
 */
export type PaymentMethod =
  | "CASH"
  | "BANK_TRANSFER"
  | "CHECK"
  | "GIRO"
  | "CREDIT_CARD"
  | "DEBIT_CARD"
  | "E_WALLET"
  | "OTHER";

export const PAYMENT_METHOD_LABELS: Record<PaymentMethod, string> = {
  CASH: "Tunai",
  BANK_TRANSFER: "Transfer Bank",
  CHECK: "Cek",
  GIRO: "Giro",
  CREDIT_CARD: "Kartu Kredit",
  DEBIT_CARD: "Kartu Debit",
  E_WALLET: "E-Wallet",
  OTHER: "Lainnya",
};

/**
 * Sort Options for Invoice List
 */
export const INVOICE_SORT_OPTIONS = [
  { value: "invoiceNumber", label: "Nomor Invoice" },
  { value: "invoiceDate", label: "Tanggal Invoice" },
  { value: "dueDate", label: "Tanggal Jatuh Tempo" },
  { value: "totalAmount", label: "Total Tagihan" },
  { value: "customerName", label: "Nama Customer" },
  { value: "createdAt", label: "Tanggal Dibuat" },
] as const;

/**
 * Type guard to check if value is a valid payment status
 */
export function isPaymentStatus(value: string): value is PaymentStatus {
  return ["UNPAID", "PARTIAL", "PAID", "OVERDUE"].includes(value);
}

/**
 * Type guard to check if value is a valid payment method
 */
export function isPaymentMethod(value: string): value is PaymentMethod {
  return ["CASH", "BANK_TRANSFER", "CHECK", "GIRO", "CREDIT_CARD", "DEBIT_CARD", "E_WALLET", "OTHER"].includes(value);
}

/**
 * Helper function to format currency
 */
export function formatCurrency(value: string | number): string {
  const num = typeof value === "string" ? Number(value) : value;
  return `Rp ${num.toLocaleString("id-ID")}`;
}

/**
 * Helper function to format date
 */
export function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString("id-ID", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/**
 * Helper function to check if invoice is overdue
 */
export function isInvoiceOverdue(invoice: Invoice): boolean {
  if (invoice.paymentStatus === "PAID") {
    return false;
  }
  const dueDate = new Date(invoice.dueDate);
  const today = new Date();
  return dueDate < today;
}
