// Purchase Invoice Types
// Matches backend DTOs in backend/internal/dto/purchase_invoice_dto.go

// ============================================================================
// ENUMS & CONSTANTS
// ============================================================================

export const PURCHASE_INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_STATUS = {
  UNPAID: 'UNPAID',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
} as const;

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHECK: 'CHECK',
  GIRO: 'GIRO',
  CREDIT_CARD: 'CREDIT_CARD',
  OTHER: 'OTHER',
} as const;

export type PurchaseInvoiceStatus = keyof typeof PURCHASE_INVOICE_STATUS;
export type PaymentStatus = keyof typeof PAYMENT_STATUS;
export type PaymentMethod = keyof typeof PAYMENT_METHOD;

// ============================================================================
// REQUEST DTOs
// ============================================================================

export interface CreatePurchaseInvoiceItemRequest {
  purchaseOrderItemId?: string;
  goodsReceiptItemId?: string;
  productId: string;
  unitId: string;
  quantity: string;
  unitPrice: string;
  discountAmount?: string;
  discountPct?: string;
  taxAmount?: string;
  notes?: string;
}

export interface CreatePurchaseInvoiceRequest {
  // invoiceNumber is auto-generated by backend based on company format settings
  invoiceDate: string; // ISO date string
  dueDate: string; // ISO date string
  supplierId: string;
  purchaseOrderId?: string;
  goodsReceiptId?: string;
  discountAmount?: string;
  taxRate?: string;
  paymentTermDays?: number;
  notes?: string;
  items: CreatePurchaseInvoiceItemRequest[];
}

export interface UpdatePurchaseInvoiceRequest {
  invoiceDate?: string;
  dueDate?: string;
  supplierId?: string;
  discountAmount?: string;
  taxRate?: string;
  paymentTermDays?: number;
  notes?: string;
  status?: PurchaseInvoiceStatus;
}

export interface ApprovePurchaseInvoiceRequest {
  notes?: string;
}

export interface RejectPurchaseInvoiceRequest {
  reason: string;
}

export interface RecordPaymentRequest {
  paymentNumber: string;
  paymentDate: string; // ISO date string
  amount: string;
  paymentMethod: PaymentMethod;
  reference?: string;
  bankAccountId?: string;
  notes?: string;
}

// ============================================================================
// RESPONSE DTOs
// ============================================================================

export interface PurchaseInvoiceItemResponse {
  id: string;
  purchaseOrderItemId?: string;
  goodsReceiptItemId?: string;
  productId: string;
  productCode: string;
  productName: string;
  unitId: string;
  unitName: string;
  quantity: string;
  unitPrice: string;
  discountAmount: string;
  discountPct: string;
  taxAmount: string;
  lineTotal: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseInvoicePaymentResponse {
  id: string;
  paymentNumber: string;
  paymentDate: string;
  amount: string;
  paymentMethod: PaymentMethod;
  reference?: string;
  bankAccountId?: string;
  notes?: string;
  createdBy: string;
  updatedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseInvoiceResponse {
  id: string;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string;
  supplierId: string;
  supplierName: string;
  supplierCode?: string;
  purchaseOrderId?: string;
  poNumber?: string;
  goodsReceiptId?: string;
  grNumber?: string;
  subtotalAmount: string;
  discountAmount: string;
  taxAmount: string;
  taxRate: string;
  totalAmount: string;
  paidAmount: string;
  remainingAmount: string;
  paymentTermDays: number;
  status: PurchaseInvoiceStatus;
  paymentStatus: PaymentStatus;
  notes?: string;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectedReason?: string;
  taxInvoiceNumber?: string;
  taxInvoiceDate?: string;
  createdBy: string;
  updatedBy?: string;
  createdAt: string;
  updatedAt: string;
  items?: PurchaseInvoiceItemResponse[];
  payments?: PurchaseInvoicePaymentResponse[];
}

// ============================================================================
// FILTERS & PAGINATION
// ============================================================================

export interface PurchaseInvoiceFilters {
  search?: string;
  supplier_id?: string;
  status?: PurchaseInvoiceStatus;
  payment_status?: PaymentStatus;
  date_from?: string;
  date_to?: string;
  due_date_from?: string;
  due_date_to?: string;
  page?: number;
  page_size?: number;
  sort_by?: 'invoiceNumber' | 'invoiceDate' | 'dueDate' | 'totalAmount' | 'createdAt';
  sort_order?: 'asc' | 'desc';
}

export interface PaginationResponse {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface PurchaseInvoiceListResponse {
  success: boolean;
  data: PurchaseInvoiceResponse[];
  pagination: PaginationResponse;
}

export interface PurchaseInvoiceDetailResponse {
  success: boolean;
  data: PurchaseInvoiceResponse;
}

// ============================================================================
// UI HELPER TYPES
// ============================================================================

export interface PurchaseInvoiceFormData {
  invoiceNumber: string;
  invoiceDate: Date;
  dueDate: Date;
  supplierId: string;
  purchaseOrderId?: string;
  goodsReceiptId?: string;
  discountAmount: string;
  taxRate: string;
  paymentTermDays: number;
  notes: string;
  items: PurchaseInvoiceItemFormData[];
}

export interface PurchaseInvoiceItemFormData {
  id?: string; // For editing existing items
  purchaseOrderItemId?: string;
  goodsReceiptItemId?: string;
  productId: string;
  productName?: string;
  productCode?: string;
  unitId: string;
  unitName?: string;
  quantity: string;
  unitPrice: string;
  discountAmount: string;
  discountPct: string;
  taxAmount: string;
  lineTotal: string;
  notes: string;
}

export interface PaymentFormData {
  paymentNumber: string;
  paymentDate: Date;
  amount: string;
  paymentMethod: PaymentMethod;
  reference: string;
  bankAccountId?: string;
  notes: string;
}
